version: "3.9"

services:
  simvascularapp:
    build: 
      context: .
      network: host
    container_name: simvascularapp
    restart: unless-stopped
    networks:
      - simvascular_net
    expose:
      - "14500"
    volumes:
      - /home/users/azhar/simv-projects:/projects
    environment:
      - XPRA_PORT=14500

  simvascular-nginx:
    image: nginx:latest
    container_name: simvascular-nginx
    restart: unless-stopped
    networks:
      - simvascular_net
    ports:
      - "172.20.23.20:80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - simvascularapp
    environment:
      - NGINX_WORKER_PROCESSES=4

networks:
  simvascular_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.16.0/20
